apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc
spec:
  capacity:
   storage: 5Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: grafana
  mountOptions:
   - hard
   - nfsvers=4.1
  nfs:
   path: /opt/intel/itm
   server: {{ .Values.setup_config.controllerIP }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-certs
spec:
  capacity:
   storage: 5Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: grafana-certs
  mountOptions:
   - hard
   - nfsvers=4.1
  nfs:
   path: /opt/intel/itm
   server: {{ .Values.setup_config.controllerIP }}
