{
 "title": "ITM Channel 0",
 "tags": [ "channel" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Collisions Detected",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Collisions Count",
     "measurement": "collisions_data",
     "query": "SELECT last(\"channel0collision\") - first(\"channel0collision\") FROM \"collisions_data\" WHERE $timeFilter",
     "refresh": "5s",
     "select": [
      [
       { "params": [ "channel0collision" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Collision and Near Miss",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Collisions",
     "measurement": "collisions_data",
     "refresh": "5s",
     "select": [
      [
       { "params": [ "channel0collision" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Near Miss",
     "measurement": "collisions_data",
     "refresh": "5s",
     "select": [
      [
       { "params": [ "channel0near miss" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inferred Stream",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Vehicles Detected",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Car Count",
     "measurement": "channel0",
     "query": "SELECT last(\"car_count\") - first(\"car_count\") FROM \"channel0\" WHERE $timeFilter",
     "refresh": "5s",
     "select": [
      [
       { "params": [ "car_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pedestrians Detected",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "channel0",
     "query": "SELECT last(\"people_count\") - first(\"people_count\") FROM \"channel0\" WHERE $timeFilter",
     "refresh": "5s",
     "select": [
      [
       { "params": [ "people_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traffic Flow",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 3, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Vehicles",
     "measurement": "channel0",
     "refresh": "5s",
     "select": [
      [
       { "params": [ "car_count" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Pedestrians",
     "measurement": "channel0",
     "refresh": "5s",
     "select": [
      [
       { "params": [ "people_count" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Bikes",
     "measurement": "channel0",
     "refresh": "5s",
     "select": [
      [
       { "params": [ "bicycle_count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Traffic Analysis",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Vehicles",
     "measurement": "channel0",
     "query": "SELECT last(\"car_count\") - first(\"car_count\") FROM \"channel0\" WHERE $timeFilter",
     "refresh": "5s",
     "select": [
      [
       { "params": [ "car_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Pedestrians",
     "measurement": "channel0",
     "query": "SELECT last(\"people_count\")  -  first(\"people_count\") FROM \"channel0\" WHERE $timeFilter",
     "refresh": "5s",
     "select": [
      [
       { "params": [ "people_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Bikes",
     "measurement": "channel0",
     "query": "SELECT last(\"bicycle_count\") - first(\"bicycle_count\") FROM \"channel0\" WHERE $timeFilter",
     "refresh": "5s",
     "select": [
      [
       { "params": [ "bicycle_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Collision and Near Miss",
   "type": "graph",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Collisions",
     "measurement": "collisions_data",
     "query": "SELECT last(\"channel0collision\") - first(\"channel0collision\") FROM \"collisions_data\" WHERE $timeFilter",
     "refresh": "5s",
     "select": [
      [
       { "params": [ "channel0collision" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Near Miss",
     "measurement": "collisions_data",
     "query": "SELECT last(\"channel0near miss\") - first(\"channel0near miss\") FROM \"collisions_data\" WHERE $timeFilter",
     "refresh": "5s",
     "select": [
      [
       { "params": [ "channel0near miss" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bikes Detected",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "channel0",
     "query": "SELECT last(\"bicycle_count\") -  first(\"bicycle_count\") FROM \"channel0\" WHERE $timeFilter",
     "refresh": "5s",
     "select": [
      [
       { "params": [ "bicycle_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}