{
 "title": "ITM",
 "tags": [ "ITM" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Collisions Detected",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Total Collision Count",
     "measurement": "total_count",
     "query": "SELECT last(\"total_collision_count\") - first(\"total_collision_count\") FROM \"total_count\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "total_collision_count" ], "type": "field" },
       {
        "params": [],
        "type": "first"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MapUI",
   "type": "ryantxu-ajax-panel",
   "gridPos": { "h": 20, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Vehicles Detected",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Vehicles",
     "measurement": "total_count",
     "query": "SELECT last(\"total_car_count\")  - first(\"total_car_count\")FROM \"total_count\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "total_car_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Pedestrians Detected",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Pedestrians",
     "measurement": "total_count",
     "query": "SELECT last(\"total_people_count\") - first(\"total_people_count\") FROM \"total_count\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "total_people_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bikes Detected",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "total_count",
     "query": "SELECT last(\"total_bicycle_count\") - first(\"total_bicycle_count\") FROM \"total_count\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "total_bicycle_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Collision Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "alias": "Collision Details",
     "measurement": "collisions_event",
     "query": "SELECT details FROM collisions_event WHERE $timeFilter",
     "select": [
      [
       { "params": [ "details" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}